#!/bin/sh

xlabel="degree"

while getopts x:s:r:t: opt
do
	case $opt in
	x ) xlabel=$OPTARG;;
	s ) sample=$OPTARG;;
	t ) title=$OPTARG;;
	r ) frange=$OPTARG;;
	esac
done
shift $(expr $OPTIND - 1)

if [ -z "$1" ]; then echo "need something to plot!" >&2; exit 1; fi
if [ -z "$sample" ]; then echo "need a sample name (-s)" >&2; exit 1; fi
if [ -z "$title" ]; then echo "need a title (-t)" >&2; exit 1; fi
if [ -n "$frange" ]; then
	hi=${frange#*:}
	lo=${frange%:*}
	rangestr=", x<$lo? 0/0: x>$hi? 0/0: fr(x) title \"best-fit in [$lo,$hi] - sample \\\"$sample\\\"\""
fi

name=${1%.dat}

gnuplot << EOF
set terminal svg size 800,600
set title "log1p-frequency against log1p-$xlabel for $title"
set output "$name.svg"
set xrange [0:]
set yrange [0:]
set ylabel "log1p-frequency"
set xlabel "log1p-$xlabel"

mf=1; cf=1; ff(x)=mf*x+cf
fit ff(x) "$1" using 1:2 via mf,cf

mr=1; cr=1; fr(x)=mr*x+cr
fit [$frange] fr(x) "$1" using 1:2 via mr,cr

plot "$1" using 1:2 title "sample \"$sample\"", \\
  ff(x) title "best-fit - sample \"$sample\"" $rangestr
EOF
