#!/bin/sh

while getopts d: opt
do
	case $opt in
	d )	basedir=$OPTARG;;
	esac
done
shift $(expr $OPTIND - 1)

if [ -n "$basedir" ]; then
	if [ ! -d "$basedir" ]; then echo "not a directory: $basdir"; exit 1; fi
	echo "patching ptables"; $0 "$basedir/ptb.graphml"
	echo "patching tgraphs"; $0 "$basedir/tgr/"*
	echo "patching indexes"; $0 "$basedir/idx/"*
	exit
fi

# igraph writes integer attributes as double attributes.
# this changes all attribute names of the form base_? from double to int type
exec sed -i 's/attr\.name="base_\(\w\)" attr\.type="double"/attr.name="base_\1" attr.type="int"/g' "$@"
